### ISSUE TITLE
Problems with mobile editing

### ISSUE THREAD

**Issue by nazo2004** [aleho/onlyoffice-ce-docker-license#18]
Hello. Thanks for the great software!

I can't insert a shape or a photo in mobile editing. This worked fine in the original version.

Software used
Nextcloud 20.0.0
Onlyoffice 6.2.2.21
Docker version 20.10.5

**Comment by aleho** [comment]
Can confirm. Will need investigation, probably some new checks somewhere.

**Comment by aleho** [comment]
Apparently most functions besides simple editing were patched out after v5.5.0.94.

I tried to bring back as much as possible which pretty much works here (in browser in mobile mode). For the Nextcloud app I cannot say for sure, neither which features are missing. Pretty much everything that was developed after v5.5.0.94 will be missing as well.

The web-apps are licensed AGPL and the code seems to have been rewritten to make the existing classes extendable to bring back all features they removed from the mobile version for paying customers.

So in my opinion if they are extending the AGPL licensed mobile editors they are currently violating the AGPL which clearly states that you cannot mix incompatible licenses or not publish code deriving from AGPL code (GPL is a viral license).

**Comment by tsunamaru** [comment]
@aleho can I help you in testing that?
On latest main, mobile editor closes with "an error occured during the work with the document".
```
==> /var/log/onlyoffice/documentserver/docservice/out.log <==,
[2021-05-17T11:12:19.545] [ERROR] nodeJS - changesError: docId = 2086436070 Error: Uncaught TypeError: info.asc_getFlags is not a function Script: https://nextcloud.****:9980/6.2.2-21/web-apps/apps/spreadsheeteditor/mobile/app.js Line: 47425:39 userAgent: Mozilla/5.0 (Android 10) Mobile Nextcloud-android/3.16.0 platform: Linux armv8l isLoadFullApi: true isDocumentLoadComplete: false StackTrace: TypeError: info.asc_getFlags is not a function,
    at child.onApiSelectionChanged (https://nextcloud.****:9980/6.2.2-21/web-apps/apps/spreadsheeteditor/mobile/app.js:47425:39),
    at executeBound (https://nextcloud.****:9980/6.2.2-21/web-apps/apps/spreadsheeteditor/mobile/app.js:762:67),
    at Ha.<anonymous> (https://nextcloud.****:9980/6.2.2-21/web-apps/apps/spreadsheeteditor/mobile/app.js:775:14),
    at Ha.<anonymous> (https://nextcloud.****:9980/6.2.2-21/web-apps/apps/spreadsheeteditor/mobile/app.js:128:29),
    at Ha.trigger (https://nextcloud.****:9980/6.2.2-21/sdkjs/cell/sdk-all-min.js:819:375),
    at Ea.c3b (https://nextcloud.****:9980/6.2.2-21/sdkjs/cell/sdk-all.js:8521:133),
    at wd.Tl.kDa (https://nextcloud.****:9980/6.2.2-21/sdkjs/cell/sdk-all-min.js:1031:221),
    at Array.<anonymous> (https://nextcloud.****:9980/6.2.2-21/sdkjs/cell/sdk-all-min.js:879:247),
    at wd.Fif (https://nextcloud.****:9980/6.2.2-21/sdkjs/cell/sdk-all-min.js:879:370),
    at wd.TOb (https://nextcloud.****:9980/6.2.2-21/sdkjs/cell/sdk-all-min.js:1041:364)
```

**Comment by nazo2004** [comment]
Do you delete the cache of your web browser?

**Comment by tsunamaru** [comment]
This isn't browser, it's Nextcloud android app.

**Comment by nazo2004** [comment]
If you are using Android, I think you can delete the cache from the application information item.

**Comment by tsunamaru** [comment]
Tried already, didn't work.

**Comment by nazo2004** [comment]
I'm sorry. I can't help you with that.

**Comment by aleho** [comment]
Cache clearing is a good idea (you'll probably have to do this if the version numbers don't change).

The error in spread-sheet editor is caused by a wrong call. Trying to fix in current main now.

**Comment by aleho** [comment]
I'm afraid the current state is all I can do.

There's probably a bug here or there to be found, but I'm not going to spend days implementing stuff they already implemented but took away (probably violating the GPL in that process).
