### ISSUE TITLE
Docker file 6.0 TCP ECONNREFUSED ERROR

### ISSUE THREAD

**Issue by techsolo12** [aleho/onlyoffice-ce-docker-license#5]
Hello Alex,

today i pulled your new image from dockerhub.
I installed it like the old images. But with the new one i become some critical errors.
When i **builded** from scratch like you, it will work like a charm. 

```
2020-10-19T12:56:01.671] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
[2020-10-19T12:56:01.671] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
[2020-10-19T12:56:01.671] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
[2020-10-19T12:56:01.671] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
```
I installed it like this:

```
sudo docker pull alehoho/oo-ce-docker-license
sudo docker run -d --name=onlyoffice -p 80:80 --restart=always alehoho/oo-ce-docker-license

sudo docker ps
sudo docker exec -it onlyoffice /bin/bash
nano /etc/onlyoffice/documentserver/local.json

// Changed part of this file
      "token": {
        "enable": {
          "request": {
            "inbox": true,                        
            "outbox": true
          },
          "browser": true
        },
        "browser": {
                "secretFromInbox": true
        },
        "inbox": {
          "header": "Authorization"
        },
        "outbox": {
          "header": "Authorization"
        }
      },
      "secret": {
        "inbox": {
          "string": "KeinEinfachesPasswort"
        },
        "outbox": {
          "string": "KeinEinfachesPasswort"
        },
        "session": {
          "string": "KeinEinfachesPasswort"
        }
      }
```

I'm sorry for my bad english skills :/ But a big thank you for your work at this repo!

**Comment by aleho** [comment]
There's nothing changed related to RabbitMQ connections, the image is built upon the official one. You can have a look at the Dockerfile and patch to verify that.

I'm suspecting your setup is broken somehow, as for me RabbitMQ and the doc server are running without issues.

If you take a look at the upstream config file, you'll see an important setting related to the AMQP setup. Maybe your config file is missing it.

```JSON
{
  "services": {
    "CoAuthoring": {
      "sql": {
        "type": "postgres",
        "dbHost": "localhost",
        "dbPort": "5432",
        "dbName": "onlyoffice",
        "dbUser": "onlyoffice",
        "dbPass": "onlyoffice"
      },
      "token": {
        "enable": {
          "request": {
            "inbox": false,
            "outbox": false
          },
          "browser": false
        },
        "inbox": {
          "header": "Authorization"
        },
        "outbox": {
          "header": "Authorization"
        }
      },
      "secret": {
        "inbox": {
          "string": "secret"
        },
        "outbox": {
          "string": "secret"
        },
        "session": {
          "string": "secret"
        }
      }
    }
  },
  "rabbitmq": {
    "url": "amqp://guest:guest@localhost"
  }
}
```

**Comment by aleho** [comment]
FYI: I just rebuilt and pushed the image to be absolutely sure. Still works here without issues.

**Comment by techsolo12** [comment]
I build the setup from a my proxmox template with docker and run it as a lxc container.
All my conatiners with docker will based on this template and work like a charm.

I will try your rebuilded image later or tomorrow also i will check the upstream config to verify it.
I update this "issue" when i know some new.
Thank you for your help 👍

**Comment by techsolo12** [comment]
I have some news. The fault was in the docker image.

I have cloned my template, pull the rebuilded image and it worked with the same config.
I do everything like before. The same template, the same config only with your rebuilded image.

Thank you for your fast help. 👍

**Comment by aleho** [comment]
I doubt that the image is to blame. It runs without issues here on two machines (I didn't update after rebuilding because it was already fine).
As I said, I'm not changing anything related to the setup, just the docserver and converter are build from sources.

I suspect due to LXC being a different environment than Docker there could be in incompatibilities (or still some error on your side that I you made the first time).

Have you tried pulling and running with Docker / podman?

**Comment by techsolo12** [comment]
LXC is a Containersystem in Proxmox. I created a LXC with Debian 10 and installed Docker, Docker compose and Portainer.
The same setup with version 5.6.5 and the same config. All my Docker images runs in seperate LXC Container with Docker fine.
Also i have installed 2 times with the "fault" 6.0 image.

A college with Proxmox had the same setup, but on a intel nuc. He had the same error.

**Comment by aleho** [comment]
Just for the sake of completeness, here's the log output of a container run on a Debian server. Can't see anything wrong.

```
 * Starting PostgreSQL 10 database server
   ...done.
 * Starting RabbitMQ Messaging Server rabbitmq-server
   ...done.
Starting supervisor: supervisord.
 * Starting periodic command scheduler cron
   ...done.
 * Starting nginx nginx
   ...done.
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
ds:docservice: stopped
ds:docservice: started
ds:converter: stopped
ds:converter: started
 * Reloading nginx configuration nginx
   ...done.
==> /var/log/onlyoffice/documentserver/converter/err.log <==

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2020-10-18T11:39:47.286] [WARN] nodeJS - update cluster with 4 workers
[2020-10-18T11:39:47.300] [WARN] nodeJS - worker 820 started.
[2020-10-18T11:39:47.305] [WARN] nodeJS - worker 826 started.
[2020-10-18T11:39:47.321] [WARN] nodeJS - worker 827 started.
[2020-10-18T11:39:47.333] [WARN] nodeJS - worker 833 started.
[2020-10-18T11:41:04.892] [WARN] nodeJS - update cluster with 4 workers
[2020-10-18T11:41:04.904] [WARN] nodeJS - worker 928 started.
[2020-10-18T11:41:04.908] [WARN] nodeJS - worker 934 started.
[2020-10-18T11:41:04.912] [WARN] nodeJS - worker 935 started.
[2020-10-18T11:41:04.918] [WARN] nodeJS - worker 941 started.

==> /var/log/onlyoffice/documentserver/docservice/err.log <==

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2020-10-18T06:49:23.621] [WARN] nodeJS - Express server starting...
[2020-10-18T06:49:23.627] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2020-10-18T06:49:23.693] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2020-10-18T11:39:48.858] [WARN] nodeJS - Express server starting...
[2020-10-18T11:39:48.863] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2020-10-18T11:39:48.918] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2020-10-18T11:41:03.370] [WARN] nodeJS - Express server starting...
[2020-10-18T11:41:03.375] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2020-10-18T11:41:03.418] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode

==> /var/log/onlyoffice/documentserver/metrics/err.log <==

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
  gauges: { 'statsd.timestamp_lag': 0 },
  timer_data: {},
  counter_rates:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  sets: {},
  pctThreshold: [ 90 ] }
18 Oct11:39:47 - [786] reading config file: ./config/config.js
18 Oct11:39:47 - server is up INFO

==> /var/log/onlyoffice/documentserver/nginx.error.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/err.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/out.log <==
[2020-10-18T06:49:22.501] [WARN] nodeJS - start cluster with 1 workers
[2020-10-18T06:49:22.512] [WARN] nodeJS - worker 6849 started.
[2020-10-18T06:49:23.281] [WARN] nodeJS - Express server starting...
[2020-10-18T06:49:23.415] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode
[2020-10-18T11:39:47.258] [WARN] nodeJS - start cluster with 1 workers
[2020-10-18T11:39:47.272] [WARN] nodeJS - worker 814 started.
[2020-10-18T11:39:48.485] [WARN] nodeJS - Express server starting...
[2020-10-18T11:39:48.665] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode
```

**Comment by techsolo12** [comment]
Your right there is nothing wrong or faultly. I don't know why it's not work with old image.
But with the new one it's so everything is cool. :) Thank you for your support :)

**Comment by aleho** [comment]
No worries, glad it works now!

Feel free to open an issue anytime. (For some reason I don't quite trust the `buildah push` command, or the Docker registry, whoever's responsible).
